//! Ledger writes and reads (CLAUDE.md §7).
//!
//! There is exactly one function in this crate that appends stock movement —
//! [`record`] — and there is none at all that updates `item_stock`. The cached
//! balance is the trigger's business.

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use sqlx::PgPool;
use store_core::ledger::{Movement, TxnType};
use uuid::Uuid;

use crate::error::{DbError, FoundExt, Result};

/// Everything needed to append one movement.
///
/// The `movement` field carries item, sign and type as a `store-core` value, so
/// the sign rules are decided in the domain rather than at the call site.
#[derive(Debug, Clone)]
pub struct NewMovement {
    pub movement: Movement,
    pub operator_id: Uuid,
    pub session_id: Option<Uuid>,
    pub machine_id: Option<Uuid>,
    pub reason_id: Option<Uuid>,
    pub note: Option<String>,
    /// Cost snapshot. When `None`, the item's current `unit_cost` is captured.
    pub unit_cost: Option<Decimal>,
    pub device_ts: Option<DateTime<Utc>>,
    /// §12: generated by the tablet before the row can reach the server, so a
    /// replayed offline outbox deduplicates instead of double-booking.
    pub client_txn_uuid: Option<Uuid>,
}

/// A ledger row as read back, with the names an operator would recognise.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LedgerRow {
    pub id: i64,
    pub item_id: Uuid,
    pub item_code: String,
    pub description: String,
    pub delta_qty: Decimal,
    pub txn_type: String,
    pub operator_id: Uuid,
    pub operator_name: String,
    pub session_id: Option<Uuid>,
    pub machine_id: Option<Uuid>,
    pub machine_code: Option<String>,
    pub reason_id: Option<Uuid>,
    pub reason_code: Option<String>,
    pub note: Option<String>,
    pub unit_cost: Option<Decimal>,
    pub device_ts: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub reverses_id: Option<i64>,
}

/// What the tablet shows after a confirmed transaction.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MovementReceipt {
    pub ledger_id: i64,
    pub item_id: Uuid,
    pub delta_qty: Decimal,
    /// The balance after this movement, read back from the cached read model.
    pub on_hand: Decimal,
    pub alert_state: String,
    /// True when this row is the one that pushed the item into LOW or EMPTY —
    /// the tablet turns this into *"This item is now LOW — storekeeper
    /// notified."*
    pub crossed_threshold: bool,
    pub created_at: DateTime<Utc>,
}

/// Append one movement and return the resulting balance.
///
/// Runs in a transaction so the ledger insert, the trigger's balance update and
/// the read-back are one atomic step. If the §7 guard refuses the movement, the
/// whole thing rolls back and nothing is recorded — the ledger is what
/// happened, not what was attempted.
pub async fn record(pool: &PgPool, new: &NewMovement) -> Result<MovementReceipt> {
    // An offline outbox replay must be a no-op, not a second issue. Checking
    // first keeps the common path cheap; the unique index is what actually
    // guarantees it under a race.
    if let Some(client_uuid) = new.client_txn_uuid {
        if let Some(existing) = find_by_client_uuid(pool, client_uuid).await? {
            return Ok(existing);
        }
    }

    let mut tx = pool.begin().await?;
    let appended = append(&mut tx, new).await;

    match appended {
        Ok(receipt) => {
            tx.commit().await?;
            Ok(receipt)
        }
        Err(err) => {
            drop(tx);
            answer_replay_from_ledger(pool, new, err).await
        }
    }
}

/// A replay that raced the attempt it was replaying, answered from the ledger.
///
/// The check at the top of [`record`] loses this race by construction: both
/// attempts read nothing, both insert, and the second one meets the unique
/// index on `client_txn_uuid`. The stock is right either way — one row, one
/// deduction — but the *caller* was being told `Conflict`, and a conflict is
/// what the terminal shows an operator as a movement that failed. It did not
/// fail; it committed on the attempt this one raced. An operator who believes
/// that re-enters the issue by hand, which is the double deduction the dedup
/// exists to prevent, arriving through the front door.
///
/// Not a narrow case: the terminal gives up on its own deadline while the
/// request may still be running, and then re-sends.
///
/// The re-read is the discriminator, and it is why this needs no constraint
/// name. A row carrying *our* `client_txn_uuid` exists only if this movement is
/// already in the ledger, whichever index actually fired; if none exists, the
/// conflict was about something else and the error goes back untouched.
async fn answer_replay_from_ledger(
    pool: &PgPool,
    new: &NewMovement,
    err: DbError,
) -> Result<MovementReceipt> {
    if !matches!(err, DbError::Conflict(_)) {
        return Err(err);
    }
    let Some(client_uuid) = new.client_txn_uuid else {
        return Err(err);
    };
    match find_by_client_uuid(pool, client_uuid).await? {
        Some(existing) => Ok(existing),
        None => Err(err),
    }
}

/// Append several movements as one atomic step.
///
/// §11's multi-machine issue: one operator taking one item for several machines
/// is one decision, and the ledger records it as one row per machine so
/// consumption stays attributable. Splitting it into separate requests would
/// let the second fail after the first committed — the operator would be told
/// the transaction was refused while part of it sat in the ledger, which is the
/// one outcome the §7 guard exists to prevent. It also cannot work over the
/// wire: §10 closes the session on the first submit.
///
/// The §7 negative-stock guard therefore applies to the *set*: if the last
/// split would overdraw the bin, every row rolls back, not just that one.
pub async fn record_many(
    pool: &PgPool,
    movements: &[NewMovement],
) -> Result<Vec<MovementReceipt>> {
    match append_batch(pool, movements).await {
        Ok(receipts) => Ok(receipts),
        // The same race as [`record`], one transaction wider: the whole batch
        // rolls back, so its rows are either all present from the attempt that
        // won or genuinely absent. Answer from the ledger only when every one
        // of them is there — a partial match is a different failure and must
        // not be dressed up as a success.
        Err(err) if matches!(err, DbError::Conflict(_)) => {
            let mut receipts = Vec::with_capacity(movements.len());
            for new in movements {
                let Some(client_uuid) = new.client_txn_uuid else {
                    return Err(err);
                };
                match find_by_client_uuid(pool, client_uuid).await? {
                    Some(existing) => receipts.push(existing),
                    None => return Err(err),
                }
            }
            Ok(receipts)
        }
        Err(err) => Err(err),
    }
}

async fn append_batch(
    pool: &PgPool,
    movements: &[NewMovement],
) -> Result<Vec<MovementReceipt>> {
    let mut tx = pool.begin().await?;
    let mut receipts = Vec::with_capacity(movements.len());

    for new in movements {
        // Replay of a partially-acknowledged batch: answer the rows already in
        // the ledger from the ledger, and append only what is missing.
        if let Some(client_uuid) = new.client_txn_uuid {
            if let Some(existing) = find_by_client_uuid_conn(&mut tx, client_uuid).await? {
                receipts.push(existing);
                continue;
            }
        }
        receipts.push(append(&mut tx, new).await?);
    }

    tx.commit().await?;

    Ok(receipts)
}

/// The insert itself, on a caller-supplied connection so one transaction can
/// span several appends. Never public: [`record`] and [`record_many`] are the
/// only ways stock moves.
async fn append(tx: &mut sqlx::PgConnection, new: &NewMovement) -> Result<MovementReceipt> {
    let prior_alert_state = sqlx::query_scalar!(
        "select alert_state from item_stock where item_id = $1",
        new.movement.item_id
    )
    .fetch_optional(&mut *tx)
    .await?;

    let inserted = sqlx::query!(
        r#"
        insert into stock_ledger (
            item_id, delta_qty, txn_type, operator_id, session_id,
            machine_id, reason_id, note, unit_cost, device_ts,
            reverses_id, client_txn_uuid
        )
        values (
            $1, $2, $3, $4, $5, $6, $7, $8,
            coalesce($9, (select unit_cost from items where id = $1)),
            $10, $11, $12
        )
        returning id, created_at, delta_qty
        "#,
        new.movement.item_id,
        new.movement.delta_qty,
        new.movement.txn_type.as_str(),
        new.operator_id,
        new.session_id,
        new.machine_id,
        new.reason_id,
        new.note.as_deref(),
        new.unit_cost,
        new.device_ts,
        new.movement.reverses_id,
        new.client_txn_uuid,
    )
    .fetch_one(&mut *tx)
    .await
    .map_err(|e| DbError::from_sqlx(e, "transaction"))?;

    let stock = sqlx::query!(
        r#"select on_hand, alert_state from item_stock where item_id = $1"#,
        new.movement.item_id
    )
    .fetch_one(&mut *tx)
    .await?;

    let crossed_threshold = prior_alert_state
        .as_deref()
        .is_some_and(|prior| prior != stock.alert_state)
        && stock.alert_state != "OK";

    Ok(MovementReceipt {
        ledger_id: inserted.id,
        item_id: new.movement.item_id,
        // Read back rather than echoed: the stored value is the one the ledger
        // will be reconciled against, and it carries the column's scale.
        delta_qty: inserted.delta_qty,
        on_hand: stock.on_hand,
        alert_state: stock.alert_state,
        crossed_threshold,
        created_at: inserted.created_at,
    })
}

/// Look up a previously recorded movement by the tablet's own transaction id.
///
/// Public because the API layer has to answer a replay *before* it authorises
/// the session: an idempotency key means "this exact request was already
/// processed", and re-authorising it would refuse a transaction that is already
/// in the ledger.
pub async fn find_by_client_uuid(
    pool: &PgPool,
    client_txn_uuid: Uuid,
) -> Result<Option<MovementReceipt>> {
    find_by_client_uuid_conn(&mut *pool.acquire().await?, client_txn_uuid).await
}

/// As [`find_by_client_uuid`], on a caller-supplied connection so a batch can
/// check for its own replays inside the transaction it is about to write.
async fn find_by_client_uuid_conn(
    conn: &mut sqlx::PgConnection,
    client_txn_uuid: Uuid,
) -> Result<Option<MovementReceipt>> {
    let row = sqlx::query!(
        r#"
        select l.id, l.item_id, l.delta_qty, l.created_at,
               s.on_hand as "on_hand!", s.alert_state as "alert_state!"
          from stock_ledger l
          join item_stock s on s.item_id = l.item_id
         where l.client_txn_uuid = $1
        "#,
        client_txn_uuid
    )
    .fetch_optional(&mut *conn)
    .await?;

    Ok(row.map(|r| MovementReceipt {
        ledger_id: r.id,
        item_id: r.item_id,
        delta_qty: r.delta_qty,
        on_hand: r.on_hand,
        alert_state: r.alert_state,
        // A replay is not a fresh crossing; the banner already fired the first
        // time this row was accepted.
        crossed_threshold: false,
        created_at: r.created_at,
    }))
}

/// Fetch a single ledger row as the domain sees it.
pub async fn get_entry(pool: &PgPool, id: i64) -> Result<store_core::LedgerEntry> {
    let row = sqlx::query!(
        r#"
        select id, item_id, delta_qty, txn_type, operator_id, session_id,
               machine_id, reason_id, note, unit_cost, device_ts, created_at,
               reverses_id
          from stock_ledger where id = $1
        "#,
        id
    )
    .fetch_optional(pool)
    .await?
    .or_not_found("ledger entry")?;

    Ok(store_core::LedgerEntry {
        id: row.id,
        item_id: row.item_id,
        delta_qty: row.delta_qty,
        txn_type: row.txn_type.parse()?,
        operator_id: row.operator_id,
        session_id: row.session_id,
        machine_id: row.machine_id,
        reason_id: row.reason_id,
        note: row.note,
        unit_cost: row.unit_cost,
        device_ts: row.device_ts,
        created_at: row.created_at,
        reverses_id: row.reverses_id,
    })
}

/// Correct a mistake by appending its mirror image (§7).
///
/// Never edits or deletes the original — the append-only trigger would refuse
/// anyway, but the point is that the audit trail keeps both halves, so somebody
/// asking where forty inserts went gets the whole story.
pub async fn reverse(
    pool: &PgPool,
    entry_id: i64,
    operator_id: Uuid,
    note: Option<String>,
) -> Result<MovementReceipt> {
    let original = get_entry(pool, entry_id).await?;

    if original.reverses_id.is_some() {
        return Err(DbError::Invalid(
            "that row is itself a reversal; reverse the original instead".into(),
        ));
    }

    let movement = Movement::reversal_of(&original)?;

    record(
        pool,
        &NewMovement {
            movement,
            operator_id,
            session_id: None,
            machine_id: original.machine_id,
            reason_id: original.reason_id,
            note: note.or_else(|| Some(format!("reversal of ledger row {entry_id}"))),
            unit_cost: original.unit_cost,
            device_ts: None,
            client_txn_uuid: None,
        },
    )
    .await
    .map_err(|e| match e {
        // The partial unique index on reverses_id caught a double correction.
        DbError::Conflict(_) => {
            DbError::Conflict(format!("ledger row {entry_id} has already been reversed"))
        }
        other => other,
    })
}

/// Filters for `GET /api/v1/ledger` (§11).
#[derive(Debug, Clone, Default)]
pub struct LedgerFilter {
    pub item_id: Option<Uuid>,
    pub operator_id: Option<Uuid>,
    pub machine_id: Option<Uuid>,
    pub txn_type: Option<TxnType>,
    pub from: Option<DateTime<Utc>>,
    pub to: Option<DateTime<Utc>>,
    pub limit: i64,
    pub offset: i64,
}

/// Paginated ledger history.
///
/// Ordered and filtered on `created_at` — what the server observed — never on
/// `device_ts` (§9.3). A drifting terminal clock must not be able to reorder
/// history or move a transaction into a different month's report.
pub async fn list(pool: &PgPool, filter: &LedgerFilter) -> Result<Vec<LedgerRow>> {
    let rows = sqlx::query_as!(
        LedgerRow,
        r#"
        select l.id           as "id!",
               l.item_id      as "item_id!",
               i.item_code    as "item_code!",
               i.description  as "description!",
               l.delta_qty    as "delta_qty!",
               l.txn_type     as "txn_type!",
               l.operator_id  as "operator_id!",
               o.full_name    as "operator_name!",
               l.session_id,
               l.machine_id,
               m.code         as "machine_code?",
               l.reason_id,
               r.code         as "reason_code?",
               l.note,
               l.unit_cost,
               l.device_ts,
               l.created_at   as "created_at!",
               l.reverses_id
          from stock_ledger l
          join items i     on i.id = l.item_id
          join operators o on o.id = l.operator_id
          left join machines m     on m.id = l.machine_id
          left join reason_codes r on r.id = l.reason_id
         where ($1::uuid is null or l.item_id = $1)
           and ($2::uuid is null or l.operator_id = $2)
           and ($3::uuid is null or l.machine_id = $3)
           and ($4::text is null or l.txn_type = $4)
           and ($5::timestamptz is null or l.created_at >= $5)
           and ($6::timestamptz is null or l.created_at < $6)
         order by l.created_at desc, l.id desc
         limit $7 offset $8
        "#,
        filter.item_id,
        filter.operator_id,
        filter.machine_id,
        filter.txn_type.map(|t| t.as_str()),
        filter.from,
        filter.to,
        filter.limit.clamp(1, 1000),
        filter.offset.max(0),
    )
    .fetch_all(pool)
    .await?;

    Ok(rows)
}

/// One item whose cached balance disagrees with its ledger.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Drift {
    pub item_id: Uuid,
    pub item_code: String,
    /// What `item_stock` claims.
    pub cached_on_hand: Decimal,
    /// What `SUM(delta_qty)` says actually happened.
    pub ledger_sum: Decimal,
}

impl Drift {
    pub fn difference(&self) -> Decimal {
        self.cached_on_hand - self.ledger_sum
    }
}

/// Recompute every balance from raw history and report disagreements.
///
/// §7: **any drift is a bug, not a data-entry problem.** This is the query
/// behind `store-cli reconcile`, and it is the reason the cached read model is
/// safe to trust on the fast path.
pub async fn reconcile(pool: &PgPool) -> Result<Vec<Drift>> {
    let rows = sqlx::query_as!(
        Drift,
        r#"
        select s.item_id                             as "item_id!",
               i.item_code                           as "item_code!",
               s.on_hand                             as "cached_on_hand!",
               coalesce(sum(l.delta_qty), 0)         as "ledger_sum!"
          from item_stock s
          join items i on i.id = s.item_id
          left join stock_ledger l on l.item_id = s.item_id
         group by s.item_id, i.item_code, s.on_hand
        having s.on_hand <> coalesce(sum(l.delta_qty), 0)
         order by i.item_code
        "#
    )
    .fetch_all(pool)
    .await?;

    Ok(rows)
}
